version: "3"

services:
    # social-network-server:
    #     build: ./server
    #     # restart: always
    #     ports:
    #         - 5000:5000
    #     environment:
    #         - TZ=Europe/Moscow

    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        volumes:
          - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
          - db_data:/var/lib/mysql
        environment:
          - SQL_INTERNAL_PORT=3306
          - MYSQL_ROOT_PASSWORD=mypass1234
          - MYSQL_DATABASE=sn
volumes:
  db_data: {}