version: "3"

services:
    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        expose:
            - 3306
        volumes:
          - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
          - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
          - SQL_INTERNAL_PORT=3306
          - MYSQL_ROOT_PASSWORD=mypass1234
          - MYSQL_DATABASE=sn

    social-network-server:
        build: ./server
        restart: always
        ports:
            - 5000:5000
        environment:
            - TZ=Europe/Moscow
            - MYSQL_HOST=db
            - MYSQL_USER=root
            - MYSQL_PASSWORD=mypass1234
            - MYSQL_DATABASE=sn
        depends_on:
            - db

volumes:
  db_data: {}