###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
   "email": "test4@test.com",
   "password": "password1",
    "name": "Vasiliy",
    "last_name": "Vasil'ev",
    "birthdate": "1999-04-04",
    "gender": true,
    "city": "New Yourk",
    "interests": "aljdflajsflkj"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
   "email": "test1@test.com",
   "password": "password1"
}


####

GET http://localhost:5000/api/auth/ping


####

GET http://localhost:5000/api/account/ping

####

GET http://localhost:5000/api/account/test1@test.com
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlhdCI6MTYzNDUwNjg5OSwiZXhwIjoxNjM0NTkzMjk5fQ.Q5nb4cRUN-iGxpQWXpV-OjN9YowaLarP8rZNcMvDza0



####
POST http://localhost:5000/api/account/friend
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlhdCI6MTYzNDUwNjg5OSwiZXhwIjoxNjM0NTkzMjk5fQ.Q5nb4cRUN-iGxpQWXpV-OjN9YowaLarP8rZNcMvDza0

{
    "target_account_id": "test4@test.com"
}